services:
  mongodb:
    image: mongo:7
    container_name: mongodb-achados-perdidos
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: achadosperdidos
    volumes:
      - mongodb_data:/data/db
    command: mongod --auth

volumes:
  mongodb_data:
